# ARRAY INDEXING

Author - poojan

---


In [1]:
import numpy as np

---


### Indexing and Slicing of Vectors 

---

In [2]:
a1 = np.arange(1,10)
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a1[8]  #box bracket is used to call index value 

np.int64(9)

In [7]:
a1[0:5]

array([1, 2, 3, 4, 5])

In [8]:
a1[5:]

array([6, 7, 8, 9])

In [15]:
aslice = a1[3:6]
aslice


array([4, 5, 6])

---


### Indexing and Slicing of Matrix 

---

In [18]:
a2 = np.arange(1,31).reshape(6,5)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [22]:
a2[3]             # It gives value on x axis like in cartesian plane 

array([16, 17, 18, 19, 20])

In [39]:
a2[0:6,0:2]       # It gives values on y axis by slicing.

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [40]:
a2[2:4,2:4]        # Small Sliced part of full matrix. 

array([[13, 14],
       [18, 19]])

In [38]:
a2[3:5,1:4]        # 2*3 matrix sliced from main 6*5 matrix and we can also save this sliced value in different variable

array([[17, 18, 19],
       [22, 23, 24]])

## bool Indexing

In [57]:
a3 = np.arange(1,11)
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
BI = a3%2==0
BI

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [59]:
a3 = a3[BI]
a3

array([ 2,  4,  6,  8, 10])