#### Author - **Poojan**

# Array Operations

---

In [3]:
import numpy as np

---


### Arithmetic Operations

---

In [14]:
a1 = np.arange(1,6)
a2 = np.arange(6,11)
a1,a2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [15]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [16]:
a1 -a2 

array([-5, -5, -5, -5, -5])

In [17]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [19]:
a2 / a1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [20]:
a2 // a1

array([6, 3, 2, 2, 2])

---

## Broadcasting

---

In [21]:
a1

array([1, 2, 3, 4, 5])

In [22]:
b = a1+100 
b                              # Here i broadcast 100 in array. We can perform any arithmetic operations.  

array([101, 102, 103, 104, 105])

In [23]:
a3 = np.arange(1,26).reshape(5,5)
a3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
b1 = a3 + 100                  # Here i broadcast 100 in array(in matrix form). We can perform any arithmetic operations.
b1

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125]])

___

### Deep and Shallow Copy

----

In [26]:
a4 = np.arange(1,11)
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
a5 = a4[0:4]
a5

array([1, 2, 3, 4])

In [31]:
# Now what you thing if i make changes in sliced array a5 then it will reflect in a4 or not 
# no it will not reflect cause a5 has its own different shallow copy in Ram. let's see.a1

In [32]:
a5 * 2

array([2, 4, 6, 8])

In [34]:
a4 # Still Same as original. 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
# but this thing is nbot possible in List.

---

In [45]:
a5 = np.arange(1,11)     #deepcopy example
a5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
a6 = a5  
a6[0]= 200

In [47]:
a5 # changes will reflect in a5 also. this is called deep copy when we save full array in other variable,for slicing it follow shallow copy

array([200,   2,   3,   4,   5,   6,   7,   8,   9,  10])

---


### Matrix Operations

---

#### Matrix multiplication

In [51]:
A = np.array([[1,2],[3,4]])
B = np.array([[4,5],[6,7]])

In [53]:
A ,B

(array([[1, 2],
        [3, 4]]),
 array([[4, 5],
        [6, 7]]))

In [54]:
# now lets do dot product of both arrays

In [56]:
A @ B #or np.dot(A,B)

array([[16, 19],
       [36, 43]])

---

#### Now lets see Transpose of Matrix

---

In [58]:
A.T

array([[1, 3],
       [2, 4]])

In [60]:
B.T

array([[4, 6],
       [5, 7]])

---


## Advance array Manipulations 

---


#### Stacking array

In [72]:
b3 = np.arange(1,6)
b4 = np.arange(6,11)  #Here we cannot use matrix we have to use vector form only.
b3 ,b4

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [73]:
# now lets stack it vertically horizontally and normal stack

In [74]:
np.vstack((b3,b4))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [75]:
np.hstack((b3,b4))


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
np.column_stack((b3,b4))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

---

### Splitting of Array

---

In [80]:
c1 = np.arange(16).reshape(4,4)
c1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
np.vsplit(c1,2) # Here it is split in vertial form

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [83]:
np.hsplit(c1,2) # Here it is split into Horizontal form remember it must spilt in equal values.

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [86]:
np.hsplit(c1,4) 


[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

----