In [3]:
import numpy as np


## Basic Array creation

In [10]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Vector and Matrix

In [11]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array Generating Functions

#### arange function


In [15]:
p = np.arange(1,10)
p

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Zeros Function

In [20]:
test = np.zeros(9)
test

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
test1 = np.zeros((4,4))
test1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### Ones Function

In [29]:
test2 = np.ones(10)
test2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
test3 = np.ones((4,4), dtype=int)
test3

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [45]:
test4 = np.ones((4,4), )
test4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

___

#### Linspace Function

#### space between every element is linear thats why it is call linspace

In [77]:
test5 = np.linspace(1,10,,dtype=int)
test5

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

-----

#### Random Generation Function

In [164]:
test6 = np.random.rand(1)
test6

array([0.95735527])

In [208]:
test7 = np.random.randint(1,9,size= (3,3))
test7

array([[6, 2, 2],
       [3, 1, 6],
       [4, 6, 6]], dtype=int32)

---

### Array attributes


In [32]:
test8 =np.random.randint(9,size=(3,4),dtype=int)
test8

array([[6, 1, 6, 5],
       [1, 5, 5, 6],
       [4, 5, 3, 7]], dtype=int32)

In [33]:
test8.shape

(3, 4)

In [34]:
test8.size

12

In [35]:
test8.dtype

dtype('int32')

### Array Methods

In [40]:
a1 = np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12]))
a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [58]:
a1.sum(axis=1)

array([ 6, 15, 24, 33])

In [45]:
a1.min()

np.int64(1)

In [47]:
a1.max()

np.int64(12)

In [48]:
a1.sum()

np.int64(78)

In [59]:
test8.mean() 

np.float64(4.5)

In [60]:
test8.std()

np.float64(1.848422751068236)

In [61]:
test8.argmin()

np.int64(1)

In [63]:
test8.argmax()

np.int64(11)

## Reshaping and Resizing

In [85]:
test9= np.arange(1,10)
test9

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
test9.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])