In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,31)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [17]:
arr1=arr1.reshape(6,5)

In [5]:
arr1.argmax()

np.int64(29)

In [6]:
arr1.argmin()


np.int64(0)

In [11]:
arr1.shape

(30,)

In [8]:
arr1.size

30

In [12]:
arr1.shape

(30,)

In [15]:
arr1[0]

np.int64(1)

In [19]:
arr1[0]

array([1, 2, 3, 4, 5])

In [20]:
arr1.shape

(6, 5)

In [36]:
arr2 = np.random.randn(6,5 )+3

In [37]:
arr2

array([[2.3479873 , 1.7305384 , 4.68839044, 2.71541517, 3.05072855],
       [1.21274447, 3.1210019 , 3.10706032, 2.48105003, 3.65296707],
       [4.78633071, 2.40656456, 2.53702441, 4.47388491, 1.04048733],
       [2.7378627 , 3.98310094, 3.34048135, 2.30104401, 5.73826047],
       [4.95903164, 1.69391784, 2.75651563, 3.05830684, 1.89096949],
       [4.70207785, 2.53505725, 3.54302331, 2.39514513, 3.21723449]])

In [39]:
arr2 *3

array([[ 7.04396189,  5.1916152 , 14.06517133,  8.14624551,  9.15218566],
       [ 3.63823341,  9.3630057 ,  9.32118097,  7.44315008, 10.95890121],
       [14.35899213,  7.21969367,  7.61107323, 13.42165472,  3.121462  ],
       [ 8.2135881 , 11.94930283, 10.02144404,  6.90313202, 17.21478141],
       [14.87709492,  5.08175351,  8.26954689,  9.17492051,  5.67290847],
       [14.10623356,  7.60517175, 10.62906992,  7.18543538,  9.65170348]])

In [45]:
arr2 = arr2.round()

In [46]:
arr2

array([[2., 2., 5., 3., 3.],
       [1., 3., 3., 2., 4.],
       [5., 2., 3., 4., 1.],
       [3., 4., 3., 2., 6.],
       [5., 2., 3., 3., 2.],
       [5., 3., 4., 2., 3.]])

In [47]:
np.sort(arr2,axis=0)

array([[1., 2., 3., 2., 1.],
       [2., 2., 3., 2., 2.],
       [3., 2., 3., 2., 3.],
       [5., 3., 3., 3., 3.],
       [5., 3., 4., 3., 4.],
       [5., 4., 5., 4., 6.]])

In [50]:
np.sort(arr2,axis=1,)


array([[2., 2., 3., 3., 5.],
       [1., 2., 3., 3., 4.],
       [1., 2., 3., 4., 5.],
       [2., 3., 3., 4., 6.],
       [2., 2., 3., 3., 5.],
       [2., 3., 3., 4., 5.]])

In [ ]:
#there any many things stack full zeros ones bool indexing 

In [52]:
arr2%2 ==1 

array([[False, False,  True,  True,  True],
       [ True,  True,  True, False, False],
       [ True, False,  True, False,  True],
       [ True, False,  True, False, False],
       [ True, False,  True,  True, False],
       [ True,  True, False, False,  True]])

In [56]:
arr2[(arr2%2==0) & (arr2%2==1)]

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''