In [1]:
import numpy as np

In [2]:
a1 = np.arange(1,31)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [3]:
a1.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [4]:
a1.min()

np.int64(1)

In [5]:
a1.max()

np.int64(30)

In [6]:
a1.sum()

np.int64(465)

In [7]:
a1.argmax()

np.int64(29)

In [8]:
a1.argmin()

np.int64(0)

In [9]:
a1.dtype

dtype('int64')

In [10]:
a2 = np.zeros([3,5])
a2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
a3 = np.ones([2,2])
a3

array([[1., 1.],
       [1., 1.]])

In [12]:
a4 = np.full([4,4],9)
a4

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [13]:
a4.flatten()

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [14]:
a4.ravel()

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [15]:
type(a4)

numpy.ndarray

In [16]:
a4.sum()

np.int64(144)

In [17]:
a1.mean()

np.float64(15.5)

In [18]:
a1 = a1.reshape(5,6)
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [19]:
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [20]:
a1.mean()

np.float64(15.5)

In [21]:
a1.real

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [22]:
a1.imag

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [23]:
a1.std()

np.float64(8.65544144839919)

In [24]:
a1.flags


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [25]:
a1.ndim

2

In [26]:
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [27]:
a1.sum(axis=1) #rowwise

array([ 21,  57,  93, 129, 165])

In [28]:
a1.sum(axis=0) #rowwise

array([65, 70, 75, 80, 85, 90])

In [29]:
a1.nbytes

240

In [30]:
a5=a1.ravel()

In [31]:
a6=a1.flatten

In [32]:
a1.nbytes

240

In [33]:
a1.sort(axis=0)

In [34]:
a1



array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [35]:
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [36]:
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [37]:
a1.astype(float)


array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30.]])

In [41]:
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [43]:
a2 = np.isnan(a1)
a2

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [44]:
a2

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [47]:
a1.astype(str)

array([['1', '2', '3', '4', '5', '6'],
       ['7', '8', '9', '10', '11', '12'],
       ['13', '14', '15', '16', '17', '18'],
       ['19', '20', '21', '22', '23', '24'],
       ['25', '26', '27', '28', '29', '30']], dtype='<U21')

In [50]:
a1[0]=9

In [51]:
a1

array([[ 9,  9,  9,  9,  9,  9],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [52]:
a1[0,0]

np.int64(9)

In [54]:
a1[:,2]

array([ 9,  9, 15, 21, 27])

In [55]:
a1[0:3,1:3]

array([[ 9,  9],
       [ 8,  9],
       [14, 15]])

In [56]:
p = a1%2==0

In [57]:
p

array([[False, False, False, False, False, False],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True]])

In [59]:
r=a1[p]
r

array([ 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [60]:
len(r)

12

In [63]:
np.split(a1,5)

[array([[9, 9, 9, 9, 9, 9]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30]])]